export const DARK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#0d1322' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#0d1322' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#4a5168' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#6b7280' }] },
  { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#101626' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#1d2438' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#0d1322' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#2a334d' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#1d2438' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#8b92a5' }] },
  { featureType: 'road.local', elementType: 'labels.text.fill', stylers: [{ color: '#4a5168' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#142a22' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#4a5168' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#142a22' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#161c2e' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0a1428' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#2a3349' }] },
  { featureType: 'building', elementType: 'geometry', stylers: [{ color: '#161c2e' }] },
]
